name = "backend"
main = "src/index.ts"
compatibility_date = "2024-12-31"

 [vars]
 DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiNjk2ZjVmYTctYmE3Yi00MGM4LTlmMzItNTNmMDUyNDFkOTE3IiwidGVuYW50X2lkIjoiYzUxYzFlZjI0NGE0NGMxZmY0MDI1YTlhNzhhNWI5OWZkMzI1MjUzNmNmYmI1NDcyM2IxNmU0NGQxN2E0NThhZiIsImludGVybmFsX3NlY3JldCI6IjgyOWU4ZTk1LTU2NzMtNDM3ZC04MzM2LTY4ZWM4NGIzNTA4ZiJ9.qwMMv_1pkc1neOWH7s9wqrpsVvVEuKrD2bcIXiGpwTA"
